- Classes/ViewHelpers/Resource/LanguageViewHelper.php
- Tests/Unit/ViewHelpers/Resource/LanguageViewHelperTest.php
This is a new ViewHelper which reads a language file and returns all the translations from.
A specific language key (e.g. ```'de'```) can be defined to forces getting all translation from a different language instead of the current browsing language.
Furthermore, this viewhelper provides the argument ```jsonEncode``` for returning all the translations as a JSON object instead of an array. This may could be useful if the translations need to be used in frontend (client side).
Of course, there is already a separate Format/Json ViewHelper available. But in my opinion, it is more inconvenient for integrators to wrap this viewhelper tag once more just for reformating as well as it is worse from the performance side of view.
> [FEATURE] New ViewHelper which gets all translations from a certain language file

- Classes/ViewHelpers/Iterator/MergeViewHelper.php
Allow use like:
{abc -> v:iterator.merge(a: def)}
This makes it easier to join multiple arrays
in a row and also to workaround some cases
where the Fluid-parser might otherwise
have a hard time.
> [FEATURE] iterator.merge: Allow use in a chain

- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
This patch fixes:
- when ``useShortcutUid="true"`` submenu items can not be fetched because of the overridden UID in the page record array
- shortcuts in a multilanguage setup are always translated with the target page overlay
> [BUGFIX] Use original page uid for submenu rendering and correct page overlay

- Classes/ViewHelpers/Media/YoutubeViewHelper.php
- Tests/Unit/ViewHelpers/Media/YoutubeViewHelperTest.php
Added some useful options for the YouTube viewhelper like hide control or video quality.
Also added some small unit test comparing the generated source url.
> [TASK] Add more options to youtube viewhelper and unittest

- Classes/ViewHelpers/Media/YoutubeViewHelper.php
In IE10, IE11 the youtube player ignores its z-index.
You need to set this parameter to make the player behave like it’s
expected.
See
http://stackoverflow.com/questions/4050999/youtube-iframe-wmode-issue
for further details.
> [TASK] Add wmode param to YoutubeViewHelper

- Classes/ViewHelpers/LViewHelper.php
The arguments of the `l` viewhelper were not registered so i added them.
Update LViewHelper.php
Update LViewHelper.php
[BUGFIX] Update L Viewhelper for Typo3 7.1
> [BUGFIX] Arguments L viewhelper not registered

- Classes/ViewHelpers/Content/RenderViewHelper.php
The content variable still needs to be imploded as otherwise this
was GetViewHelper behaviour
Resolves #783
> [BUGFIX] Implode by linefeed

- Classes/ViewHelpers/Media/AbstractMediaViewHelper.php
`TYPO3_SITE_URL` always comes with a trailing slash ...
> [BUGFIX] Remove redundant slash in URL

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
using of `cObjGetSingle('RECORDS', $conf)` instead of `RECORDS($conf)` which will be deprecated in TYPO3 8.0.
Also checking TYPO3 Version in `\ViewHelpers\Media\Image\AbstractImageViewHelper`and in `ViewHelpers\Resource\AbstractImageViewHelper` to switch between 
* TYPO3 Version < 7.1  using `GeneralUtility::png_to_gif_by_imagemagick`
* TYPO3 Version >= 7.1 using `GraphicalFunctions::pngToGifByImagemagick`
> [TASK] Get rid of deprecation log in TYPO3 7.1

- Classes/ViewHelpers/Page/Header/MetaViewHelper.php
missing attribute "property" for e.g. to set open graph metadata in page header.
> [FEATURE] Add attribute "property" to Page\Header\MetaViewHelper

- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
If attribute was given an integer value, for example the key value of an
ForViewHelper, processPagesArgument in AbstractMenuViewHelper returns an
empty array instead of an array with the given attribute value, which
results in an empty return in render method of DirectoryViewHelper.
Added a test is_integer
> [BUGFIX] Fixed DirectoryViewHelper.Menu attribute "pages".

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
Since uid is a unique field, it's not required to group it.
The query fails on other DBMS than MySQL due to the grouping.
> [BUGFIX] Do not group by uid

- Classes/ViewHelpers/Format/EliminateViewHelper.php
- Tests/Unit/ViewHelpers/Format/EliminateViewHelperTest.php
Removes whitespaces between HTML tags and is inspired by Twig's "spaceless Tag":
http://twig.sensiolabs.org/doc/tags/spaceless.html
> [FEATURE] Add "whitespaceBetweenHtmlTags" option to EliminateViewhelper

- Classes/ViewHelpers/Page/Header/AlternateViewHelper.php
The hreflang link Tag should also include the current language. Right now it's deleted, but this is wrong behaviour.
From the [google docs](https://support.google.com/webmasters/answer/189077?hl=en): If you have multiple language versions of a URL, each language page must identify all language versions, **including itself**.
> [BUGFIX] AlternateViewHelper should include a link to current language

- Classes/ViewHelpers/Page/BreadCrumbViewHelper.php
- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
The names of those variables can be set via view helper arguments so they should not be hardcoded.
Fix for #845.
> [BUGFIX] Do not hardcode menu backup variables

- Classes/Utility/CoreUtility.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
In TYPO3 7.1 the flag icons were moved, see: [TYPO3 7.1 Changes](http://wiki.typo3.org/TYPO3.CMS/Releases/7.1/Breaking#Breaking:_.2364143_-_Language_.2F_Country_Flag_files_moved)
Solves #854
> [BUGFIX] Use the correct flag icon path depended on the current core version

- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
Currently overlay values are only used if not empty which leads to unexpected behavior regarding link title generation in menus. A page may provide values for nav_title *and* title in ``L=0`` but only for title in ``L=1`` resulting in a not translated menu item. I'm not aware of unwanted side effects but YMMV.
> [BUGFIX] Force overriding with overlay values

- .travis.yml
This is a workaround until > 7.1 TYPO3 is working with FT3 testing concept.
> [BUGFIX] Set travis to 7.1

- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
Filtering of pages depending on their translation state is processed after fetching menu items for a given menu which eventually results in a wrong item count for submenus. Fixes #904
> [BUGFIX] Hide non translated pages if configured

- Classes/Traits/ConditionViewHelperTrait.php
- Classes/ViewHelpers/Condition/Context/IsBackendViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsCliViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsDevelopmentViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsFrontendViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsProductionViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsTestingViewHelper.php
- Tests/Unit/ViewHelpers/AbstractViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsBackendViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsCliViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsDevelopmentViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsFrontendViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsProductionViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsTestingViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper stopped working since 7.3 because the AbstractConditionViewHelper is now compiled statically by default. Any ConditionViewHelper that implements it's own render method without taking compiling into account currently simple fail by showing their "false/else" result as soon as they are executed from cache. Non-cached execution still works, which makes this problem a bit weird to catch. Aside from fixing the ViewHelpers itself the testcases are updated to verify, that the effected viewHelpers render/work the same in cached and uncached
context.
> [TASK] Make Condition/Context ViewHelpers static compilable

- Classes/Traits/TemplateVariableViewHelperTrait.php
- Classes/ViewHelpers/Condition/String/ContainsViewHelper.php
- Classes/ViewHelpers/Condition/String/IsLowercaseViewHelper.php
- Classes/ViewHelpers/Condition/String/IsNumericViewHelper.php
- Classes/ViewHelpers/Condition/String/IsUppercaseViewHelper.php
- Classes/ViewHelpers/Condition/String/PregViewHelper.php
- Tests/Unit/ViewHelpers/AbstractViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/String/ContainsViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/String/IsLowercaseViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/String/IsNumericViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/String/IsUppercaseViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/String/PregViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper
stopped working since 7.3 because the AbstractConditionViewHelper
is now compiled statically by default. Any ConditionViewHelper that implements
it's own render method without taking compiling into account currently
simple fail by showing their "false/else" result as soon as they are
executed from cache. Non-cached execution still works, which
makes this problem a bit weird to catch.
Aside from fixing the ViewHelpers itself the Testcases are updated to verify,
that the effected viewHelpers render/work the same in cached and uncached
context.
followup of: https://github.com/FluidTYPO3/vhs/pull/906
> [TASK] Make Condition/String ViewHelpers static compilable

- Classes/ViewHelpers/Condition/Form/HasValidatorViewHelper.php
- Classes/ViewHelpers/Condition/Form/IsRequiredViewHelper.php
- Tests/Unit/ViewHelpers/Condition/Form/HasValidatorViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Form/IsRequiredViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper stopped working since 7.3 because the AbstractConditionViewHelper is now compiled statically by default. Any ConditionViewHelper that implements it's own render method without taking compiling into account currently
simple fail by showing their "false/else" result as soon as they are executed from cache. Non-cached execution still works, which makes this problem a bit weird to catch.
Aside from fixing the ViewHelpers itself the Testcases are updated to verify, that the effected viewHelpers render/work the same in cached and uncached context.
followup of: https://github.com/FluidTYPO3/vhs/pull/906
> [TASK] Make Condition/Form ViewHelpers static compilable

- Classes/ViewHelpers/Condition/Iterator/ContainsViewHelper.php
- Classes/ViewHelpers/Iterator/IndexOfViewHelper.php
- Classes/ViewHelpers/Iterator/NextViewHelper.php
- Classes/ViewHelpers/Iterator/PreviousViewHelper.php
- Tests/Unit/ViewHelpers/Condition/Iterator/ContainsViewHelperTest.php
- Tests/Unit/ViewHelpers/Iterator/IndexOfViewHelperTest.php
- Tests/Unit/ViewHelpers/Iterator/NextViewHelperTest.php
- Tests/Unit/ViewHelpers/Iterator/PreviousViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper
stopped working since 7.3 because the AbstractConditionViewHelper
is now compiled statically by default. Any ConditionViewHelper that implements
it's own render method without taking compiling into account currently
simple fail by showing their "false/else" result as soon as they are
executed from cache. Non-cached execution still works, which
makes this problem a bit weird to catch.
Aside from fixing the ViewHelpers itself the Testcases are updated to verify,
that the effected viewHelpers render/work the same in cached and uncached
context.
> [TASK] Make Condition/Iterator ViewHelpers static compilable

- Classes/ViewHelpers/Condition/Page/HasSubpagesViewHelper.php
- Classes/ViewHelpers/Condition/Page/IsChildPageViewHelper.php
- Classes/ViewHelpers/Condition/Page/IsLanguageViewHelper.php
- Tests/Unit/ViewHelpers/Condition/Page/HasSubpagesViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Page/IsChildPageViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Page/IsLanguageViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper
stopped working since 7.3 because the AbstractConditionViewHelper
is now compiled statically by default. Any ConditionViewHelper that implements
it's own render method without taking compiling into account currently
simple fail by showing their "false/else" result as soon as they are
executed from cache. Non-cached execution still works, which
makes this problem a bit weird to catch.
Aside from fixing the ViewHelpers itself the Testcases are updated to verify,
that the effected viewHelpers render/work the same in cached and uncached
context.
> [TASK] Make Condition/Page ViewHelpers static compilable

- Classes/ViewHelpers/Condition/Variable/IsNullViewHelper.php
- Classes/ViewHelpers/Condition/Variable/IssetViewHelper.php
- Tests/Unit/ViewHelpers/Condition/Variable/IsNullViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Variable/IssetViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper stopped working since 7.3 because the AbstractConditionViewHelper is now compiled statically by default. Any ConditionViewHelper that
implements it's own render method without taking compiling into account currently simple fail by showing their "false/else" result as soon as they are executed from cache. Non-cached execution
still works, which makes this problem a bit weird to catch. 
Aside from fixing the ViewHelpers itself the Testcases are updated to verify, that the effected viewHelpers render/work the same in cached and uncached context.
> [TASK] Make Condition/Variable ViewHelpers static compilable

- Classes/ViewHelpers/Condition/Type/IsArrayViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsBooleanViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsDomainObjectViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsFloatViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsInstanceOfViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsIntegerViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsObjectViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsQueryResultViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsStringViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsTraversableViewHelper.php
- Tests/Unit/ViewHelpers/Condition/Type/IsArrayViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsBooleanViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsDomainObjectViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsFloatViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsInstanceOfViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsIntegerViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsObjectViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsQueryResultViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsStringViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Type/IsTraversableViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper stopped working since 7.3 because the AbstractConditionViewHelper is now compiled statically by default. Any ConditionViewHelper that implements it's own render method without taking compiling into account currently simple fail by showing their "false/else" result as soon as they are executed from cache. Non-cached execution still works, which makes this problem a bit weird to catch.
Aside from fixing the ViewHelpers itself the Testcases are updated to verify,
that the effected viewHelpers render/work the same in cached and uncached context.
> [TASK] Make Condition/Type ViewHelpers static compilable

- Classes/ViewHelpers/Extension/LoadedViewHelper.php
- Classes/ViewHelpers/IfViewHelper.php
- Tests/Unit/ViewHelpers/Extension/LoadedViewHelperTest.php
- Tests/Unit/ViewHelpers/IfViewHelperTest.php
many viewHelpers extending from AbstractConditionViewHelper stopped working since 7.3 because the AbstractConditionViewHelper is now compiled statically by default. Any ConditionViewHelper that
implements it's own render method without taking compiling into account currently simple fail by showing their "false/else" result as soon as they are executed from cache. Non-cached execution
still works, which makes this problem a bit weird to catch.
Aside from fixing the ViewHelpers itself the Testcases are updated to verify, that the effected viewHelpers render/work the same in cached and uncached context.
> [TASK] Make the remaining condition viewHelpers static compilable

- Classes/ViewHelpers/Format/TidyViewHelper.php
The default-encoding of `tidy_parse_string` is not utf8. Include option for encoding with default utf8-encoding.
> Include encoding-option to format.tidy-Viewhelper

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
The v:page.resources.fal view helper should look for resources pertaining to the page currently viewed by default.
At the moment, the getActiveRecord() function inherited from AbstractRecordResourceViewHelper is used which returns the current cObj and not the page record.
> [BUGFIX] Fix current page id for fal resources

- .gitattributes
In case the extension is pulled via Composer, a few files and directories can
be excluded to reduce the amount of transferred data and disk space usage.
> [TASK] Ignore some files/directories on archive export

- Classes/ViewHelpers/UnlessViewHelper.php
Inverted `f:if` which only supports negative matching.
> [FEATURE] UnlessViewHelper

- Classes/ViewHelpers/Page/Header/AlternateViewHelper.php
- Resources/Private/Schemas/Vhs.xsd
The `v:page.header.alternate` ViewHelper should, just like the `f:link.page` ViewHelper, have the option to add an existing QueryString when generating the URI. Links to, for example, news detail pages are currently generated without the query string and are therefore wrong.
> [FEATURE] Argument addQueryString for v:page.header.alternate

- ext_localconf.php
the PageRepository doesn't return url + urltype anymore which causes the rendering of that external url
to fail. This commit adds url + urltype to the rootLineFields.
> [BUGFIX] Fix external link handling in AbstractMenuViewHelper

- Classes/ViewHelpers/Media/VimeoViewHelper.php
Hi,
An ultra small PR just to remove the casting of the argument "playerId" as an integer.
On this page https://developer.vimeo.com/player/js-api, we can see that "player_id" should be a string :)
> [BUGFIX] Fix the cast of the playerId argument

- README.md
An 'i' was missing in settings (-> settngs)
> [DOC] Fix a wrong typoscript in README

- Classes/Traits/PageRendererTrait.php
- Classes/ViewHelpers/Page/FooterViewHelper.php
- Classes/ViewHelpers/Page/Header/AlternateViewHelper.php
- Classes/ViewHelpers/Page/Header/CanonicalViewHelper.php
- Classes/ViewHelpers/Page/Header/LinkViewHelper.php
- Classes/ViewHelpers/Page/Header/MetaViewHelper.php
- Classes/ViewHelpers/Page/Header/TitleViewHelper.php
As stated at 
https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Deprecation#Deprecation:_.2368074_-_Deprecate_getPageRenderer.28.29_methods 
the getPageRenderer()-function has been marked as deprecated with the release of TYPO3 7.4 and will be removed with the release of TYPO3 8.0. PageRenderer implements SingletonInterface, which means that getting a own (shared) instance of it will become mandatory.
Therefore, in favor of DRY-principle, a Trait has been introduced providing a instance of PageRenderer through GeneralUtility-instanciation.
> [BUGFIX] Fixed deprecation warnings with TSFE->getPageRenderer()

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Typolink/Index.html#typolink <-- addQueryString is a boolean with the property method which needs to be set.
> [BUGFIX] Fixed addQueryString behaviour in LanguageMenuViewHelper

- ext_emconf.php
I just noticed that vhs causes an entry in deprecation.log of TYPO3 7.6.4
> [TASK] Remove deprecated dependency

- Classes/ViewHelpers/Iterator/ColumnViewHelper.php
Adds `v:iterator.column` which allows doing everything that `array_column` in PHP does but also supporting Iterator as input.
> [FEATURE] ViewHelper for doing `array_column` on Iterator

- Classes/Service/PageService.php
- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
- Classes/ViewHelpers/Page/LinkViewHelper.php
This patch slightly reduces the number of db queries fx when generating menus by enabling ``PageService::hidePageForLanguageUid`` to accept full page records.
> [TASK] Reduce number of db queries

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
Show only live and new records in workspaces and hide moved or placeholder records, since their overlays are fetched automatically.
> Bugfix for duplicate content in workspace previews

- Classes/ViewHelpers/Resource/CollectionViewHelper.php
Fixes the problem, that the resource collection viewhelper returns the return value of `loadContents`, which is `void`, so the result is always `NULL`.
```
{v:resource.collection(uid: uid) ->  v:variable.set(name: 'records')}
```
> [BUGFIX] Collection viewhelper always returning NULL

- Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
If "moveable" is "true" then assertAllowedInFooter gives back "false"
> [BUGFIX] Assets ViewHelper. the argument "moveable" is misinterpreted.

- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Media/ImageViewHelper.php
- Classes/ViewHelpers/Media/PdfThumbnailViewHelper.php
This is not much more of a hotfix to make PDF thumbnail generation work again. Some arguments are deprecated due to changes in image viewhelpers. Closes #933.
> [BUGFIX] Adapt to recent changes in image viewhelpers

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
This patch fixes an issue when splitting up menus into main and submenus (with an entry level > 1) where root page would have itself as a single submenu entry.
> [BUGFIX] No submenus on rootpage

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
This patch fixes an issue where pages that are not to be shown in a menu due to translation settings still were rendered with empty link text.
> [BUGFIX] Remove pages not to be shown from menu

- Classes/Service/PageService.php
This change uses the correct instance of PageRepository within PageService.
Trying to access the TSFE within the TYPO3 backend would lead to a PHP Fatal Error because `$GLOBALS['TSFE']` is `null`.
I believe this was an oversight during the update to 3.0.0 or 3.0.1.
Best regards,
Maximilian Pfeifer
> [BUGFIX] Use instantiated PageRepository in PageService

- Classes/Service/AssetService.php
**Problem**
Some files created by the `AssetService` can have different file names but the same content. Depending on the complexity of the site there can be many such files that will useless take CPU time to generate and use extra disk space.
**Cause**
The problem with existing approach is that keys returned by `array_keys()` are not necessarily sorted. This causes a different md5 if same assets are added in a different order.
**Solution**
The fix is to sort asset keys before using them.
**Example**
Example of identical files (note sizes of 2nd and last file):
```
MBP3:~/Projects/*** [hotfix/1.0.8-fix-uniqueid-in-vhs-assets *] $ ls -lt www/typo3temp/vhs-assets-*.js
-rw-r--r-- 1 dmitry staff     371 Sep 21 16:26 www/typo3temp/vhs-assets-3414f3cc1a869796d0e367e72da47206.js
-rw-r--r-- 1 …
```
> [BUGFIX] Asset merge can produce many identical files

- Classes/ViewHelpers/Page/Header/CanonicalViewHelper.php
Before this patch, the ViewHelper ignored parameters set by CoolUri (and maybe Realurl as well).
Now it takes parameters either from `GeneralUtility::_GET()`, `GeneralUtility::_POST()` or both, actually adding those parameters to the generated URL.
> [BUGFIX] Fix parameter usage in v:page.header.canonical

- Classes/Traits/SourceSetViewHelperTrait.php
Uncaught TYPO3 Exception
Class 'FluidTYPO3\Vhs\Traits\MathUtility' not found 
Error thrown in file
/html/typo3/typo3conf/ext/vhs/Classes/Traits/SourceSetViewHelperTrait.php in line 93.
> [BUGFIX] Exception when you use "quality" with v:media.image

- Classes/ViewHelpers/IfViewHelper.php
- Tests/Unit/ViewHelpers/IfViewHelperTest.php
Deprecate and plan to remove `v:if` (which has the
stack condition argument) in favor of `f:if` as provided
by Fluid Standalone (which parses complex expressions).
To be removed when TYPO3v8 LTS is our minimum.
NB: deprecation logged from initializeArguments in order
to limit the number of logged deprecations to one per
request where v:if is used rather than once per execution.
> [REMOVAL] Deprecate v:if in favor of f:if

- Classes/Utility/ViewHelperUtility.php
- Tests/Unit/ViewHelpers/AbstractViewHelperTest.php
- composer.json
This patch adds a couple of changes which will be required
for an in-progress conversion of every ViewHelper which
can support it, to ideal performance when compiled.
A new dependency, namelesscoder/typo3-cms-fluid-gap,
provides the necessary API to achieve this. Slight rewriting
of the test base ensures all ViewHelpers can be tested with
proxying from render() to renderStatic().
> [TASK] Preparations for LTS-v8 compiling support bridge

- Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
- ext_conf_template.txt
- ext_localconf.php
Since Assets are the only part of VHS which cause runtime
resource usage regardless of whether you use it or not, a
toggle is added which allows disabling the Asset handling.
Doing so will not break the ViewHelpers - VHS will simply
stop processing the ViewHelpers' generated assets.
> [FEATURE] Add extension configuration toggle to disable Assets

- Classes/Traits/SourceSetViewHelperTrait.php
When in development mode, the TYPO3 backend showed PHP warnings, because the argument for method resetFrontendEnvironment() was missing.
> Bugfix: Backup TSFE to reset it later when simulating frontend environment

- Classes/ViewHelpers/Render/RequestViewHelper.php
Fixes missing argument registrations after converting to
renderStatic and CompileWithRenderStatic usage.
> [TASK] Follow-up to restore arguments on v:render.request

- .travis.yml
The causes for failures are now corrected.
> [TASK] No longer allow failures on HHVM and PHP 7.1

- Classes/ViewHelpers/Iterator/SplitViewHelper.php
- Tests/Unit/ViewHelpers/Iterator/SplitViewHelperTest.php
Provides a way to split a string into an array with $length
number of bytes of the string in each array value.
In other words, `str_split` for Fluid.
> [FEATURE] Add Iterator/Split ViewHelper for str_split

- Classes/Traits/ArrayConsumingViewHelperTrait.php
- Classes/ViewHelpers/Math/AbstractMultipleMathViewHelper.php
- Classes/ViewHelpers/Math/AbstractSingleMathViewHelper.php
- Classes/ViewHelpers/Math/AverageViewHelper.php
- Classes/ViewHelpers/Math/CeilViewHelper.php
- Classes/ViewHelpers/Math/CubeViewHelper.php
- Classes/ViewHelpers/Math/CubicRootViewHelper.php
- Classes/ViewHelpers/Math/DivisionViewHelper.php
- Classes/ViewHelpers/Math/FloorViewHelper.php
- Classes/ViewHelpers/Math/MaximumViewHelper.php
- Classes/ViewHelpers/Math/MedianViewHelper.php
- Classes/ViewHelpers/Math/MinimumViewHelper.php
- Classes/ViewHelpers/Math/ModuloViewHelper.php
- Classes/ViewHelpers/Math/PowerViewHelper.php
- Classes/ViewHelpers/Math/ProductViewHelper.php
- Classes/ViewHelpers/Math/RangeViewHelper.php
- Classes/ViewHelpers/Math/RoundViewHelper.php
- Classes/ViewHelpers/Math/SquareRootViewHelper.php
- Classes/ViewHelpers/Math/SquareViewHelper.php
- Classes/ViewHelpers/Math/SubtractViewHelper.php
- Classes/ViewHelpers/Math/SumViewHelper.php
- Tests/Unit/ViewHelpers/Math/AbstractMathViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/AverageViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/DivisionViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/MaximumViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/MinimumViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/ProductViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/RangeViewHelperTest.php
- Tests/Unit/ViewHelpers/Math/SubtractViewHelperTest.php
Also moves a utility method to detect iterators or
arrays, to the ArrayConsumingViewHelperTrait.
NB: a few esoteric bugs are also fixed with this,
mainly related to processing array arguments in
math operations. Fewer cases now cause errors.
> [TASK] Implement compile bridge in Math scope

- Classes/ViewHelpers/Page/BreadCrumbViewHelper.php
This patch addresses #1181 by only rendering typical doktypes for starting points.
> [TASK] Skip rendering of sysfolders in rootline

- Classes/ViewHelpers/Resource/AbstractResourceViewHelper.php
The correct tablename is sys_file_metadata if one use categories for files. Alternatively we can use the fieldname which is "categories".  So this whole thing will be changed to fieldname = categories. 
Discussion is very welcome
> TASK: Change tablenames in query to sys_file_metadata

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
This patch fixes all content-related ViewHelpers when
used in combination with workspaces. Solves issues
which caused live and preview workspaces to show
incorrect content or wrongly positioned content.
Fix kindly sponsored by MSI Chicago - http://www.msichicago.org/
> [BUGFIX] Fix incorrect content fetching in workspaces

- Classes/ViewHelpers/Page/InfoViewHelper.php
- Tests/Unit/ViewHelpers/Page/InfoViewHelperTest.php
This is a really pragmatic approach to fix #1114. Please be aware that no access restrictions apply here. I'm still rather for removing this viewhelper completely as we want to simplify things with vhs but try to stay as close to the core as possible. Developers who rely on this should IMHO create their own helpers to fit their use cases.
> [TASK] Loosen page record constraints

- Classes/ViewHelpers/Page/Header/LinkViewHelper.php
I think the fluid discrepancy between 7.6 and 8.x causes some tensions here.
We need to keep an eye out where there are arguments that were registered through the constructor in CMS 7.6 but need a call to `parent::inititArgs` now.
Fixes: #1100
> [BUGFIX] Register parent arguments where necessary

- Classes/ViewHelpers/Form/SelectViewHelper.php
- Classes/ViewHelpers/Format/DateRangeViewHelper.php
- Classes/ViewHelpers/Format/Json/EncodeViewHelper.php
- Classes/ViewHelpers/Format/MarkdownViewHelper.php
- Classes/ViewHelpers/Iterator/FirstViewHelper.php
- Classes/ViewHelpers/Iterator/RandomViewHelper.php
- Classes/ViewHelpers/Iterator/SortViewHelper.php
- Classes/ViewHelpers/Math/AbstractMultipleMathViewHelper.php
- Classes/ViewHelpers/Math/AbstractSingleMathViewHelper.php
- Classes/ViewHelpers/Uri/GravatarViewHelper.php
The ViewHelper Exception is imported in many places and it made sense
to annotate throwing methods directly.
Also removes some unused imports
> [TASK] Annotate throwing methods accordingly

- Classes/ViewHelpers/Variable/TyposcriptViewHelper.php
Injection is only done during instanciating with a call on ObjectManager->get(), but renderStatic is a static call, so no injection is done.
> [BUGFIX] Static injection of configurationManager failed

- Classes/ViewHelpers/Iterator/AbstractLoopViewHelper.php
- Classes/ViewHelpers/Iterator/DiffViewHelper.php
- Classes/ViewHelpers/Iterator/ExplodeViewHelper.php
- Classes/ViewHelpers/Iterator/FilterViewHelper.php
- Classes/ViewHelpers/Iterator/ForViewHelper.php
- Classes/ViewHelpers/Iterator/IndexOfViewHelper.php
- Classes/ViewHelpers/Iterator/IntersectViewHelper.php
- Classes/ViewHelpers/Iterator/KeysViewHelper.php
- Classes/ViewHelpers/Iterator/LoopViewHelper.php
- Classes/ViewHelpers/Iterator/MergeViewHelper.php
- Classes/ViewHelpers/Iterator/PushViewHelper.php
- Classes/ViewHelpers/Iterator/RangeViewHelper.php
- Classes/ViewHelpers/Iterator/ReverseViewHelper.php
- Classes/ViewHelpers/Iterator/SliceViewHelper.php
- Classes/ViewHelpers/Iterator/SortViewHelper.php
- Classes/ViewHelpers/Iterator/SplitViewHelper.php
- Classes/ViewHelpers/Iterator/UniqueViewHelper.php
- Classes/ViewHelpers/Iterator/ValuesViewHelper.php
and use (integer) instead of intval().
removed some unnecessary brackets.
> [BUGFIX] IteratorViewHelpers - insert missing $escapeOutput for TYPO3v8+

- Classes/ViewHelpers/Iterator/AbstractLoopViewHelper.php
- Classes/ViewHelpers/Iterator/ChunkViewHelper.php
- Classes/ViewHelpers/Iterator/ColumnViewHelper.php
- Classes/ViewHelpers/Iterator/DiffViewHelper.php
- Classes/ViewHelpers/Iterator/ExplodeViewHelper.php
- Classes/ViewHelpers/Iterator/ExtractViewHelper.php
- Classes/ViewHelpers/Iterator/FilterViewHelper.php
- Classes/ViewHelpers/Iterator/FirstViewHelper.php
- Classes/ViewHelpers/Iterator/ForViewHelper.php
- Classes/ViewHelpers/Iterator/ImplodeViewHelper.php
- Classes/ViewHelpers/Iterator/IndexOfViewHelper.php
- Classes/ViewHelpers/Iterator/IntersectViewHelper.php
- Classes/ViewHelpers/Iterator/KeysViewHelper.php
- Classes/ViewHelpers/Iterator/LastViewHelper.php
- Classes/ViewHelpers/Iterator/LoopViewHelper.php
- Classes/ViewHelpers/Iterator/MergeViewHelper.php
- Classes/ViewHelpers/Iterator/NextViewHelper.php
- Classes/ViewHelpers/Iterator/PopViewHelper.php
- Classes/ViewHelpers/Iterator/PreviousViewHelper.php
- Classes/ViewHelpers/Iterator/PushViewHelper.php
- Classes/ViewHelpers/Iterator/RandomViewHelper.php
- Classes/ViewHelpers/Iterator/RangeViewHelper.php
- Classes/ViewHelpers/Iterator/ReverseViewHelper.php
- Classes/ViewHelpers/Iterator/ShiftViewHelper.php
- Classes/ViewHelpers/Iterator/SliceViewHelper.php
- Classes/ViewHelpers/Iterator/SortViewHelper.php
- Classes/ViewHelpers/Iterator/SplitViewHelper.php
- Classes/ViewHelpers/Iterator/UniqueViewHelper.php
- Classes/ViewHelpers/Iterator/ValuesViewHelper.php
Inserted where necessary.
Remove $escapeOutput if set in parent classes.
> [BUGFIX] IteratorViewHelpers - insert missing $escapeChildren for TYPO3v8+

- Classes/ViewHelpers/Math/AbstractSingleMathViewHelper.php
This change avoids needless htmlspecialchars at the childrens.
> [BUGFIX] Set escaping behavior in Math ViewHelpers

- Classes/ViewHelpers/Render/CacheViewHelper.php
$renderChildrenClosure()  is now only executed if the identity doesn't exists in the cache.
> [BUGFIX] RenderCache - at each call, $renderChildrenClosure() was called

- Classes/ViewHelpers/Content/InfoViewHelper.php
and change type casting from `intval()` to `(integer)`
> [BUGFIX] Set escaping behavior in Content ViewHelpers

- Classes/ViewHelpers/Render/AsciiViewHelper.php
- Classes/ViewHelpers/Render/CacheViewHelper.php
- Classes/ViewHelpers/Render/InlineViewHelper.php
Added missing argument "arguments" for v:render.request Viewhelper - resolves #1228
> [BUGFIX] Set escaping behavior in Render ViewHelpers

- Classes/ViewHelpers/Resource/FileViewHelper.php
The Resource\FileViewHelper currently is only able to return the
attributes of requested file as an array although the underlying logic
is more powerful and could also return the actual TYPO3 File resource
instance. This instance would also be necessary to work e.g. with the
MediaViewHelper in fluid, so adding a parameter here to let the user
decide what he wants opens up new possibilities like correctly rendering
videos stored as sys_file references in flux forms.
> [FEATURE] Add onlyProperties parameter to v:resource.file

- Classes/ViewHelpers/Media/ExtensionViewHelper.php
- Classes/ViewHelpers/Media/FilesViewHelper.php
- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Media/SizeViewHelper.php
Inserts missing escaping behavior and removes $escapeOutput in ```Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php```because it is set in one of the parent classes.
> [BUGFIX] Set escaping behavior in Media ViewHelpers

- composer.json
from github or packagist. fixes #1262
> ensures that typo3-ter dependencies are fulfilled even if you install

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
reference: fix language fallback #1135
> So the better approach would be to use the defined content fallback from config.sys_language_mode.
Condition: <v:content.render pageUid="{activePageUid}" column="4" />
Tested with langs (en, uk, fr): 
- en: default language with content ✓
- uk: not translated page => shows default content ✓
- fr: translated page => shows fr content ✓
> [BUGFIX] content.render fallback language

- Classes/ViewHelpers/Page/BreadCrumbViewHelper.php
Includes all page doktpyes in breadcrumb smaller than 200
Ref: #1181
> [BUGFIX] Allow any doktypes < 200 in BreadCrumbViewHelper (#1181)

- Classes/View/UncacheTemplateView.php
`ObjectManagerInterface` doesnt seem to be resolved correctly on wakeup. - As a workaround, and since ObjectManager is a singleton anyways and thus is resolved earlier, we can grab the prepared instance without using the interface here.
Ref: https://github.com/FluidTYPO3/vhs/commit/94c3d77daffa0f9ad65c3b6136f26f0131bab90f#commitcomment-24065966
Closes #1369
> [BUGFIX] Correctly instantiate ObjectManager

- Classes/Traits/SlideViewHelperTrait.php
- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
This patch removes nearly all VHS content pulling logic, replacing it with the frontend-only ContentObjectRenderer method to getRecords().
The fix affects:
* Content overlay modes `content_fallback` and `strict` now correctly respected
* Workspace and preview overlay is now done by core internals
* Language menu generation uses same API and gets overlayed for language/workspace preview
* Content sliding slideCollect no longer overrides slide depth if slide depth is set
* Content sliding behavior reversal functionality ("slideCollectReverse" argument) restored
Close: #1297
Close: #1321
Close: #1323
Close: #761
Close: #1049
> [BUGFIX] Correct handling of language overlays

- Classes/ViewHelpers/Format/EliminateViewHelper.php
- Tests/Unit/ViewHelpers/Format/EliminateViewHelperTest.php
str_split() fails to consider multi-byte characters, while this ViewHelper will most probably be used to remove such characters.
Resolves: #1397
> [BUGFIX] Correctly format.eliminate multibyte chars

- Classes/Service/AssetService.php
Hey there,
first of all, many thanks for VHS!
This pull request checks the position, respectively if a `head` or `body` tag exists, before inserting assets at marker.
We have websites with "services", which render small portions of HTML with no `head` or `body` tags via page types, which should not contain assets. Before VHS 4.3.0 this was possible. With VHS 4.3.0 the assets get always inserted at the top.
I don't know, if this should be handled by VHS or better by the integrator, e.g. disable assets at all by certain page types?
Thanks again!
> [BUGFIX] Check position before inserting assets at marker

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
Fixes #1422 by revoking an earlier incorrect patch.
> [BUGFIX] Revoke 'Properly use shortcut target uid'

- Classes/Service/AssetService.php
Sometimes TYPO3 caches can't be deleted with `typo3cms cache:flush --force` because of wrong file permissions of the EXT:vhs assets.
With this patch, `GeneralUtility:fixPermissions()` will be enforced to make use of `$TYPO3_CONF_VARS['BE']['fileCreateMask']`.
> [BUGFIX] enforce fixPermissions when writing asset files

- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
Utilize the PageRepository to correctly fetch resources of translated pages
that are stored in pages_language_overlay.
Resolves: https://github.com/FluidTYPO3/vhs/issues/1392
> [BUGFIX] Correctly fetch media for translated pages

- Classes/ViewHelpers/Iterator/ExtractViewHelper.php
This copies the error handling from the non-recursive version.
> [BUGFIX] Trigger error on recursive extract with invalid iterable

- Classes/ViewHelpers/Media/PictureViewHelper.php
By adding the class to the image tag it won't actually style the image, but just the picture tag.
By moving it to the default image tag, it would allow to use the class to actually style the img.
Example:
https://codepen.io/fjacobi/pen/vpqzQG
> Move class into the default image tag

- Classes/Traits/SourceSetViewHelperTrait.php
This should fix #1445 for crop arguments (but not for cropping information coming from a `FileReference`).
> [BUGFIX] Handle crop argument when adding srcset variants

- Classes/Service/PageService.php
- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
this will fix a similar issue as in the previous closed issue https://github.com/FluidTYPO3/vhs/issues/904
for a menu like this:
- Item 1 (localized)
- Subitem 1.1 (not localized)
- Subitem 1.2 (not localized)
... the Viewhelper renders the localized "Item 1" with hasSubpages=true in any/all languages
This fix extends the submenu check inside parseMenu method and makes a recursive call (on parseMenu method) to check if the submenu isn't empty after processing. Only if the processed/parsed menu isn't empty we can be sure that the current menu item has sub-pages ;)
> [BUGFIX] Set hasSubpages correctly on localized menus

- .travis.yml
- composer.json
Add replacement to typo3/cms-version in this package
as this package was removed for TYPO3 8 and merged
into typo3/cms-workspaces.
Simplify travis build by only requiring typo3/cms-core.
This is enough because all TYPO3 packages require
this package in the same version. If typo3/cms-core is required
in dev-master, all other are also installed in dev-master.
This has the additional benefit, that other direct dependencies
to TYPO3 framework packages remain unchanged, thus it is checked
by composer whether they are allowed to be installed in the version
requested for typo3/cms-core.
Add prefer-stable: true to always fetch stable versions when
possible even when composer is called without --prefer-dist.
Last but not least, replace the deprecated or operator "|"
whith the new "||" operator.
> [TASK] Allow installation of TYPO3 master

- Classes/ViewHelpers/Condition/String/IsNumericViewHelper.php
The argument value type does not match the parameter type of ctype_digit() and results in a negative check for integer values passed to the viewhelper. Using is_numeric() instead of ctype_digit() fixes the problem.
Fixes: #1471
> [BUGFIX] Fix condition.string.isNumeric viewhelper

- Classes/ViewHelpers/Format/Json/EncodeViewHelper.php
- Tests/Unit/ViewHelpers/Format/Json/EncodeViewHelperTest.php
> [BUGFIX] Remove return {} on empty value in order to allow false and null values (#1486)

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
This fixes an exception about missing TCA definition for `pages_language_overlay` in TYPO3 9.5.0+ while maintaining compatibility with lower TYPO3 versions.
Close: #1504
> [BUGFIX] Fix #1504: use "pages" instead of "pages_language_overlay" since TYPO3 9.5

- Classes/Traits/TagViewHelperTrait.php
The trimmed content was used when the tagname was empty,
but if there was a tag the content was not trimmed.
That should be unified.
Fixes: #1440
> [TASK] For a TagViewHelper use the trimmed content

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
It is now fixed by fetching page translation data from proper places according to the TYPO3 version.
> Fix #1556: language menu is still broken in TYPO3 9.x

- Classes/ViewHelpers/Condition/Context/IsCliViewHelper.php
https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.0/Breaking-72368-TYPO3ConstantsRemoved.html
> [BUGFIX] Avoid removed TYPO3_cliMode constant

- Classes/ViewHelpers/Math/DivisionViewHelper.php
- Classes/ViewHelpers/Math/MaximumViewHelper.php
- Classes/ViewHelpers/Math/MinimumViewHelper.php
- Classes/ViewHelpers/Math/ProductViewHelper.php
- Classes/ViewHelpers/Math/SubtractViewHelper.php
- Classes/ViewHelpers/Math/SumViewHelper.php
The exception is moved up to have the "guard clause" checked first.
Fixes: #1505
> Unify exception when second argument is required but missing.

- Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php
`$GLOBALS["TSFE"]->fePreview` is 2 is the preview is done from the worskpace preview mode, and 1 if the preview if done from the admin panel toggle.
getRecord should be aware of both.
Fixes #1561
> [BUGFIX] Remove HiddenRestriction in workspace preview mode

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
if variable "language" is set in the viewhelper for example "0,1", nothing return.
> [BUGFIX] Use keyword "root" for default pidInList in language mode

- Classes/Service/AssetService.php
- Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
The abstract asset viewhelper as well as the asset service still referred to a legacy `TagBuilder` alias (removed in TYPO3 10.x).
> [BUGFIX] Fix legacy TagBuilder alias reference

- Classes/ViewHelpers/Format/SubstringViewHelper.php
mb_substr() does not officially support negative $length. Use own calculation to make it work again.
Resolves: #1587
> [BUGFIX] Restore negative $length support after switch to mb_ functions

- Classes/ViewHelpers/Iterator/SortViewHelper.php
`Iterator\SortViewHelper` now checks for all forms of `\DateTimeInterface` when trying to deduce a sort value from objects
fixes #1610
> [BUGFIX] Allow sorting by DateTimeInterface

- ext_localconf.php
Variable `$_EXTCONF` not exist anymore at TYPO3 10.x.
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html?highlight=_extconf
> [BUGFIX] Fix extension config handling on TYPO3 10

- Classes/ViewHelpers/Page/LinkViewHelper.php
These method call is also missing in version 5.1.1 an in every version between. I hope you can fix it in several versions.
> added missing method call to set  at uri building

- .travis.yml
- Tests/bootstrap.php
Adds two new error-silenced builds that allow seeing E_NOTICE and E_USER_DEPRECATED warnings separately, based on TYPO3 dev-master.
> [TASK] Add fail-allowed builds for notice and deprecations

- Classes/ViewHelpers/Variable/PregMatchViewHelper.php
The existing rendering suggested at supporting `{value -> v:variable.pregMatch(...)}` but this was actually not working since the "subject" argument was required.
> Support chain notation for PregMatchViewHelper subject

- Classes/ViewHelpers/DebugViewHelper.php
- Classes/ViewHelpers/Security/DenyViewHelper.php
This has been deprecated in TYPO3v9 and dropped in TYPO3v10.
The interface is not necessary since the switch to standalone Fluid with TYPO3v8 whose `ViewHelperInterface` already contains the `setChildNodes()` method formerly defined by `ChildNodeAccessInterface`.
Fixes #1695
> Drop ChildNodeAccessInterface usage

- Classes/Service/AssetService.php
- Classes/ViewHelpers/Iterator/ExtractViewHelper.php
Fixes #1649 
- Changed FluidTYPO3\Vhs\Service\AssetService to implement LoggerAwareInterface and call $this->logger->warning() instead of GeneralUtility::sysLog()
- Added static getLogger() function to FluidTYPO3\Vhs\ViewHelpers\Iterator\ExtractViewHelper and used it to call self::getLogger()->warning() instead of GeneralUtility::sysLog()
> [BUGFIX] Replaced deprecated GeneralUtility::sysLog calls with new logging API

- Classes/ViewHelpers/Resource/AbstractResourceViewHelper.php
.. when treatAsUid=1
Those URLs appear when using a
<flux:field type="input" config="{renderType: 'inputLink'}"/>
Resolves: https://github.com/FluidTYPO3/vhs/issues/1710
> [FEATURE] Handle t3://file?uid=23 URLs in <v:resource.file> view helper

- Classes/ViewHelpers/Uri/ImageViewHelper.php
Sometimes the TYPO3v10 backend already returns absolute image URLs that do
not need to be modified anymore.
This happens for a couple of minutes only, afterwards the backend returns relative
URLs.
This patch fixes image URLs in that short timeframe.
Example of such an absolute image URL returned in the backend that needs no
further processing:
http://localhost:5707/typo3/index.php?route=/image/process&token=414b99de77e22aa555584f4c53fdb5ebb9b2deb9&id=516701
----
This happened with TYPO3 v10.4.14 and vhs 6.0.5.
> [BUGFIX] Do not process absolute image URIs in the backend

- Classes/ViewHelpers/Resource/AbstractResourceViewHelper.php
Fixup for "[FEATURE] Handle t3://file?uid=23 URLs in <v:resource.file> view helper"
The value of field
<flux:field type="input" config="{renderType: 'inputLink'}"/>
gets different values in TYPO3 v9 and v10:
- TYPO3 v9 stored the path to the filename, e.g. "fileadmin/user_upload/image.jpg"
- TYPO3 v10 stores a t3:// URL, e.g. "t3://file?uid=2342"
This patch automatically detects t3:// URLs in all image sources, regardless
if $treatAsUid is given.
That way the view helpers can load an image regardless if they have been stored
in TYPO3 v9 or v10:
<v:resource.file identifier="fileadmin/user_upload/image.jpg"/>
<v:resource.file identifier="t3://file?uid=2342"/>
> [BUGFIX] Handle both t3:// and normal file names at once

- composer.json
When upgrading an extension for TYPO3-11 it is desirable to work with as much stable releases as possible. This pull request would allow to use the dev-branch from vhs together with stable TYPO3 releases from the latest branch.
> Enable stable releases from TYPO3-11-branch with composer

- Classes/ViewHelpers/Format/EliminateViewHelper.php
.. because output is escaped by default.
See https://github.com/FluidTYPO3/vhs/issues/1475
> Mention <f:format.raw> for "whitespaceBetweenHtmlTags"

- .editorconfig
- README.md
- composer.json
- ext_emconf.php
Hi Claus, hi Björn, hi Cedric, hi VHS team,
this PR is a suggestion to align your extension documentation with the recently introduced [TYPO3 documentation standards](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html) and similar extensions.
The focus is on having one central documentation at Documentation/ and reduce the README to an abstract, badges and further links to all important aspects of the extensions (TER, docs, VCS). 
What is missing: The whole documentation should be rendered and deployed on docs.typo3.org - in perspective. It is currently deployed to the custom page https://viewhelpers.fluidtypo3.org/fluidtypo3/vhs/ and thus not found by the new global search at docs.typo3.org. If you need assistance on how to migrate, i …
> [DOCS] Align with new TYPO3 documentation standards

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
The `reverse` ViewHelper argument is not initialized by `AbstractMenuViewHelper` and not by any other MenuViewhelper that is distributed with EXT:vhs.
So most of the times -if not always- `$this->arguments` won't have the `reverse` key and we fall back to `false` which is also the default value of `getRooline()`s 2nd argument.
> [BUGFIX] Fix unsafe array access for 'reverse' argument

- Classes/Service/PageService.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
Since the introduction of native speaking URLs, the parameter has no effect
anymore:
https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html#impact
It has been removed in TYPO3v10 and throws a deprecation notice:
> TYPO3 Deprecation Notice: Setting typolink.useCacheHash has no effect anymore.
> Remove the option in all your TypoScript code and Fluid templates.
> in typo3/sysext/frontend/Classes/Typolink/PageLinkBuilder.php line 155
https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html
Resolves: https://github.com/FluidTYPO3/vhs/issues/1774
> [TASK] Do not use useCacheHash when generating links on TYPO3 9.5+

- Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php
Using $GLOBALS['TSFE']->fePreview has been deprecated in TYPO3v10 and
removed in v11. It generates a deprecation warning:
> TYPO3 Deprecation Notice: Property $TSFE->fePreview is not in use anymore
> as this information is now stored within the FrontendPreview aspect.
> in typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 4101
Relevant changelog entries:
- https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Feature-88791-IntroducePreviewAspectInContext.html
- https://docs.typo3.org/c/typo3/cms-core/11.3/en-us/Changelog/11.0/Breaking-91473-DeprecatedFunctionalityRemoved.html
This patch uses the new context aspect if it exists, and falls back
to TSFE->fePreview in old TYPO3 versions.
Resolves: https://github.com/FluidTYPO3/vhs/issues/1775
Preview a …
> [TASK] Replace TSFE->fePreview with aspect on TYPO3v10+

- Classes/ViewHelpers/Condition/Context/IsDevelopmentViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsProductionViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsTestingViewHelper.php
Fix for Issue #1783 
Under TYPO3 11 use Environment class to check context.
> Fix for Issue #1783

- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
I upgraded my project's PHP version to PHP 8.1 and got this PHP warning in the backend layout module. The issue was that $record in getResources function was empty (ViewHelpers/Resource/Record/FalViewHelper.php) and then there was no $record[$this->idField] was trying to fetch uid key's value in $record array (without isset() in else part, Line no. 147).
> [BUGFIX] PHP 8 warning fix if $record is empty in getResources func

- Classes/Service/AssetService.php
Prevents PHP 8.1 from throwing: PHP Warning: Undefined array key 2 in Classes/Service/AssetService.php
> [BUGFIX] Avoid list() in favor of null-coalesced extraction

- Classes/Traits/SourceSetViewHelperTrait.php
- Classes/ViewHelpers/Media/SourceViewHelper.php
In TYPO3 12, there is a change in the behavior of the ContentObjectRenderer. The array key 3 of the info-array returned by getImgResource() does not longer contain the relative image path for processed images. Instead, the absolute path is now returned. See https://forge.typo3.org/issues/95379
As a result, the absolute image path is used in the SourceViewHelper and the images on the page are broken. To fix this, i added a check if the image is processed. If so, the relative URL is fetched from the ProcessedFile-object. The rest of the behavior remains the same.
> [BUGFIX] Fixed Image-URL in SourceViewHelper after TYPO3 12 Update

- README.md
The old link is outdated and stuck at vhs v5.0.0
> Update link to viewhelper documentation

- Classes/ViewHelpers/Render/TemplateViewHelper.php
With this, for example the f:link.action() ViewHelper can be used in the rendered template
Resolves: #1902
> [BUGFIX] Assign resolved Request in TemplateViewHelper

- Classes/Service/AssetService.php
Website users loaded corrupted JavaScript assets for files generated by EXT:vhs when EXT:vhs was in the middle of re-writing the contents of the requested asset file. This happens because EXT:core `GeneralUtility::writeFile()` isn't implemented in an atomic style causing observers (such as visiting website users) to read incomplete asset file contents. Incomplete JavaScript files likely cause syntax errors when interpreted by the user's user-agent rendering front end sites unable to reach JavaScript-based interactivity.
Fix the issue by (non-atomically) writing into a temporary file and replacing the destination asset file with a single atomic `rename()` operation instead. This ensures that observers of the destination asset file either see the complete old contents or the complete new …
> [BUGFIX] Fix corrupted JavaScript assets loaded by website users

- Classes/Utility/ContentObjectFetcher.php
- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Render/RequestViewHelper.php
Adds a common API for reading ContentObjectRenderer instance in whichever way is appropriate for the host framework version. Tries all possible locations before giving up.
Close: #1920
> [FEATURE] Introduce ContentObjectFetcher

- Classes/Traits/SourceSetViewHelperTrait.php
- Classes/Utility/ContentObjectFetcher.php
- Classes/View/UncacheTemplateView.php
- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Content/InfoViewHelper.php
- Classes/ViewHelpers/Format/Placeholder/LipsumViewHelper.php
- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Media/SourceViewHelper.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
- Classes/ViewHelpers/Render/UncacheViewHelper.php
- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
- Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php
- Tests/Fixtures/Classes/DummyConfigurationManagerWithContentObjectRenderer.php
- Tests/Fixtures/Classes/DummySourceSetViewHelper.php
- Tests/Unit/Traits/SourceSetViewHelperTraitTest.php
Avoid issues caused by attempting to resolve ContentObjectRenderer in methods that may be called during DI compilation.
> [BUGFIX] Use late instancing of ContentObjectRenderer

- Classes/Service/AssetService.php
- Tests/Unit/Service/AssetServiceTest.php
- ext_localconf.php
Uncached rendering context no longer provides TS through ConfigurationManager. An exception is raised instead. To avoid this, we store a representation of the plugin.tx_vhs TS scope in a separate cache when the page is rendered before it is cached - and retrieve this cached TS when needed.
> [BUGFIX] Handle new TS-not-set limitation on v13

- ext_localconf.php
Commit "[BUGFIX] Avoid addRootLineFields on v13" prevented loading rootline fields on TYPO3 v12.4.26,
leading to a missing "nav_hide" field needed by the breadcrumb viewhelper.
We correctly check that it's a TYPO3 version less than 13, instead of less-or-equal than 12.4.
Related: 3b9720203c1df47fa943c01061f35116f93954ff
> [BUGFIX] Use addRootLineFields on v12.4

- Classes/Utility/ContentObjectFetcher.php
The ContentObjectFetcher was introduced to have a common API for fetching the current content object across different TYPO3 versions.
This class logs a deprecation notice in TYPO3v12:
> TYPO3 Deprecation Notice:
> ConfigurationManager->getContentObject() is deprecated since TYPO3 v12.4
> and will be removed in v13.0.
> Fetch the current content object from request attribute
> "currentContentObject" instead in
> vendor/typo3/cms-extbase/Classes/Configuration/ConfigurationManager.php
> line 96
To prevent this from happening, we check for the TYPO3 version and always use the request instead of the configuration manager in TYPO3v12+.
Related: https://github.com/FluidTYPO3/vhs/pull/1920
Related: https://github.com/FluidTYPO3/vhs/pull/1921
Related: https://github.com/FluidTYPO3/flux/pull/2229 …
> [BUGFIX] Always fetch ContentObject from request in TYPO3v12+

- Classes/ViewHelpers/Security/AbstractSecurityViewHelper.php
Fixed deprecation notice in AbstractSecurityViewHelper for implicitly marking parameter $frontendUsers as nullable:
```
[ TYPO3\CMS\Core\Error\Exception ]                                           
PHP Runtime Deprecation Notice: FluidTYPO3\Vhs\ViewHelpers\Security\Abstrac  
tSecurityViewHelper::assertFrontendUsersLoggedIn(): Implicitly marking para  
meter $frontendUsers as nullable is deprecated, the explicit nullable type   
must be used instead in /var/www/app/vendor/fluidtypo3/vhs/Classes/ViewHelp  
ers/Security/AbstractSecurityViewHelper.php line 233
```
$frontendUsers is now explicitly nullable.
> [BUGFIX] Fixed deprecation notice in AbstractSecurityViewHelper

- Classes/Service/AssetService.php
The routing request argument isn't necessarily a PageArguments instance.
> [BUGFIX] Avoid relying on PageArguments in AssetService
