- ext_localconf.php
TYPO3 core has a check and throws an error
> [TASK] Remove first backslash in hooks - v7 compatibility

- Classes/ViewHelpers/Resource/CollectionViewHelper.php
- Classes/ViewHelpers/Resource/LanguageViewHelper.php
Last occurrences of backlashes infront of the namespace.
> [TASK] CGL - Remove backslashes in use

- Classes/ViewHelpers/Render/RequestViewHelper.php
This line will never be reached.
> [TASK] CGL - Unreachable return

- CHANGELOG.md
My first attempt to write changelogs for VHS.
Unfortunately I had to put hard links to pull requests, mentioned in changelog, since [Github doesn't support Flavored Markdown for usual *.md files](http://stackoverflow.com/a/16540773/2070270) - only for commit messages, pull requests and issues.
Also I've marked breaking changes with exclamation-sign, so they are more visible.
> [DOC] Add CHANGELOG.md, containing changes from 2.0.0 to 2.2.0

- CHANGELOG.md
* Contains notes till 04.02.2015
* Trimmed endlines from spaces
* Add missing note about T3 7 support in 2.2.0
> [DOC] Add changes into CHANGELOG.md from 2.2.0

- CHANGELOG.md
* Contains notes till 17.02.2015
> [DOC] Add changes into CHANGELOG.md for upcoming 2.3.0

- Classes/ViewHelpers/Iterator/FilterViewHelper.php
Sorry I could'nt include a test for this. Since it is juste a change on an existing feature I dont understand which kind of cases I should test.
> [FEATURE] Filter by array in iterator.filter

- CHANGELOG.md
* Contains notes till 04.03.2015
> [DOC] Add changes into CHANGELOG.md for 2.3.0

- Classes/ViewHelpers/Variable/ExtensionConfigurationViewHelper.php
Replaces/Adapts: #739
Closes:  #739
> [FEATURE] ViewHelper to get settings in ext_conf_template.txt

- Classes/ViewHelpers/Iterator/SortViewHelper.php
usingsortArrayto sort $objectStorage
> [TASK] Remove duplicate code

- Classes/ViewHelpers/Iterator/FilterViewHelper.php
very useful, if you filter on a property of an object which is NULL.
> [FEATURE] Added the ability to filter null values 

- Classes/Traits/TagViewHelperTrait.php
> [BUGFIX] Don't assign empty content

- CHANGELOG.md
* Contains notes till 27.03.2015
* Added missing changes in 2.3.0
* Mentioned release date of 2.3.1 (only bugfixes, so I did not add anything into change log)
* Put new version 2.3.2 with "upcoming" release date and changes
* Remove non-needed newlines
> [DOC] Add missing changes into CHANGELOG.md for 2.3.0, mention 2.3.1

- Classes/Service/AssetService.php
- Classes/ViewHelpers/Format/Placeholder/LipsumViewHelper.php
> [TASK] Add missing argument and unify usage

- Classes/Service/PageSelectService.php
> [BUGFIX] Don't show hidden/disabled pages in menus

- Classes/ViewHelpers/Security/AbstractSecurityViewHelper.php
> [BUGFIX] Type cast uids when comparing

- Classes/Service/AssetService.php
> [BUGFIX] Don't replace urls in inline css assets

- Classes/ViewHelpers/Page/LinkViewHelper.php
> [BUGFIX] Adapt to translation behavior of menus

- Classes/ViewHelpers/Render/CacheViewHelper.php
> [BUGFIX] Use hashed identifier

- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
> [TASK] Add argument to use absolute URLs

- Classes/Service/AssetService.php
> [BUGFIX] Force closing tag and render comment

- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
> [BUGFIX] ImageViewHelper should respect fully qualified uris

- Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
> [TASK] Deprecate argument

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
> [BUGFIX] Language menu can be inactive and current (translation settings)

- Classes/ViewHelpers/Render/RequestViewHelper.php
> [BUGFIX] Removes a unsed argument

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
> [BUGFIX] Fix deprecated call to cObj->IMAGE

- Classes/ViewHelpers/Media/ExistsViewHelper.php
> [BUGFIX] Fix Exists ViewHelper for v7

- Classes/Traits/SlideViewHelperTrait.php
- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Content/Random/GetViewHelper.php
- Classes/ViewHelpers/Content/Random/RenderViewHelper.php
- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
Continuation from #679 - now with 100% more traits.
> Allow record sliding in page.resources.fal with traits

- Classes/Traits/SourceSetViewHelperTrait.php
- Classes/ViewHelpers/Media/AbstractMediaViewHelper.php
- Classes/ViewHelpers/Media/ImageViewHelper.php
- Classes/ViewHelpers/Media/PictureViewHelper.php
- Classes/ViewHelpers/Media/SourceViewHelper.php
- Tests/Unit/ViewHelpers/Media/PictureViewHelperTest.php
- Tests/Unit/ViewHelpers/Media/SourceViewHelperTest.php
PictureViewHelper is already quite steady. Srcset is still kind of rough around the edges and only added to ```v:media.image``` so far.
> [TASK] Add Responsive Images

- Classes/ViewHelpers/Random/StringViewHelper.php
> [BUGFIX] Random string viewhelper should not use off by one error

- Classes/ViewHelpers/Media/GravatarViewHelper.php
- Classes/ViewHelpers/Uri/GravatarViewHelper.php
- Tests/Unit/ViewHelpers/Media/GravatarViewHelperTest.php
- Tests/Unit/ViewHelpers/Uri/GravatarViewHelperTest.php
> [FEATURE] Gravatar viewhelper

- Classes/Service/PageSelectService.php
- Classes/ViewHelpers/Page/Menu/AbstractMenuViewHelper.php
> [BUGFIX] Take Move-To placeholders into account

- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
Removes additional adding of absRefPrefix to image sources. Fixes #915.
> [BUGFIX] Apply absRefPrefix only once

- Classes/ViewHelpers/Media/AudioViewHelper.php
> [BUGFIX] Ensure correct array index

- Classes/ViewHelpers/Page/Header/CanonicalViewHelper.php
Possible fix for #921. Requires representative testing.
> [TASK] Replace uri builder with typolink, drop visibility checks

- Classes/Service/PageSelectService.php
> [TASK] Respect possible FE group without FE user

- Classes/Traits/SourceSetViewHelperTrait.php
- Classes/ViewHelpers/Media/ImageViewHelper.php
> [TASK] Use first srcset width as default fallback src

- Classes/ViewHelpers/Variable/ExtensionConfigurationViewHelper.php
The parameter "name" existed before and was not yet optional.
It is now replaced by an optional parameter "path" to specify a path to
fetch a subpart of configuration from.
> [FEATURE] ExtensionConfiguration-VH: Allow fetching subpart of config

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
> [BUGFIX] Avoid issue if localisation is false

- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
Applies @smichaelsen fix in comment:  https://github.com/FluidTYPO3/vhs/commit/5be8bd2c7c7dc3d04266818603e7baf04c6ad670#commitcomment-14279699
> [BUGFIX] Fix for non workspaced records

- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
Fix phpDoc annotations, yoda-style comparisons and other small
improvements.
> [TASK] Cleanups in FalViewHelper

- Classes/ViewHelpers/Site/UrlViewHelper.php
https://fluidtypo3.org/viewhelpers/vhs/master/Site/UrlViewHelper.html
> [DOC] Fix rendering of Site/UrlViewHelper docs

- Classes/Asset.php
- Classes/Service/AssetService.php
- Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
- Classes/ViewHelpers/Asset/PrefetchViewHelper.php
- Classes/ViewHelpers/Asset/StyleViewHelper.php
- Tests/Unit/AssetTest.php
> [TASK] Remove deprecated argument

- Classes/ViewHelpers/Media/YoutubeViewHelper.php
So here is the PR with one commit ^^
> [TASK] Add enableJsApi parameter to YoutubeViewHelper

- Classes/Service/PageSelectService.php
> [BUGFIX] Check for empty array

- Classes/ViewHelpers/Format/ReplaceViewHelper.php
> [TASK] Use correct function for case sensitivity

- Classes/Utility/CoreUtility.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
> [BUGFIX] Adapt to SVG flag icons

- Classes/ViewHelpers/Format/Placeholder/ImageViewHelper.php
> [TASK] Force https protocol

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
> [TASK] Respect enable fields

- composer.json
- ext_emconf.php
> [TASK] Adapt PHP version constraints to TYPO3 7.6.x

- Classes/Service/PageService.php
- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
> [BUGFIX] Revoke unintended removal of doktype filtering

- Classes/Traits/TemplateVariableViewHelperTrait.php
Fixes issues with signatures of said Trait (optional/mandatory argument order and missing type hints).
> [TASK] Cleanup TemplateVariableViewHelperTrait signatures

- Classes/ViewHelpers/Iterator/UniqueViewHelper.php
Adds `v:iterator.unique` which accepts a subject and returns or assigns a new uniques-filtered array.
> [FEATURE] ViewHelper for `array_unique` on Iterators

- Classes/Traits/ArrayConsumingViewHelperTrait.php
Allows using the Trait from a static context.
> [FEATURE] Add static method variants on ArrayConsumingViewHelperTrait

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
> [BUGFIX] Re-add menu dividers

- Classes/ViewHelpers/Render/TemplateViewHelper.php
> [TASK] Adapt paths settings

- Classes/Service/PageService.php
- Classes/Traits/PageRecordViewHelperTrait.php
- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
- Classes/ViewHelpers/Page/LinkViewHelper.php
This patch enables correct shortcut handling for links generated by LinkViewHelper and adapts page access restriction related functionality from menu items.
> [FEATURE] Adapt shortcut and access restriction handling

- Classes/ViewHelpers/Iterator/ImplodeViewHelper.php
> [TASK] Override argument descriptions

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
Apply localisation so that inherited render() method will retrieve a localised version of the record. Also removes the overridden render() method on v:page.resources.fal since this method was the same as the inherited one. Now, the inherited method calls getRecord which then applies the localisation.
Close: #1007
Close: #996
> [BUGFIX] Localise every getRecord call in v:page.resources.fal

- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
This change skips resolving of any file references or file objects which are in a workspace overlay with a state of DELETED. Such files / file references will no longer be shown by (record based) FAL ViewHelpers in general.
Close: #896
> [BUGFIX] Filter deleted workspace placeholders from FAL records

- Classes/Service/PageService.php
> [BUGFIX] Instantiate new page repository for backend context

- Classes/ViewHelpers/Format/Json/EncodeViewHelper.php
> [TASK] Add sensible encoding option

- Classes/ViewHelpers/Media/ImageViewHelper.php
Thx for the cherry-pick, minimal followup, @NamelessCoder 
Ref: 5dc539f29b55b3d1568c23180e19527b3375d476
> [TASK] Remove duplicate assignments

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
> [BUGFIX] Prevent unintended auto rendering

- Classes/ViewHelpers/ConstViewHelper.php
This viewhelper renders PHP constants
> [FEATURE] Constant viewhelper

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
> [TASK] Deprecate/remove unused code

- Classes/ViewHelpers/Security/AbstractSecurityViewHelper.php
- Tests/Unit/ViewHelpers/Security/AbstractSecurityViewHelperTest.php
> [BUGFIX] Remove overwriting method

- Classes/ViewHelpers/Menu/SubViewHelper.php
> [BUGFIX] Replace call to superfluous method with service call

- Tests/Unit/ViewHelpers/Page/InfoViewHelperTest.php
Asserts that page.info behaviour is not broken.
Ref #1114
> [TASK] Test that Page/InfoViewHelper returns correct values

- Classes/Service/AssetService.php
- Classes/Service/PageService.php
- Tests/Unit/ViewHelpers/AbstractViewHelperTest.php
Just a few easy picks found while debugging
> Various small cleanups

- Classes/Traits/ArrayConsumingViewHelperTrait.php
- Classes/Traits/ConditionViewHelperTrait.php
- Classes/Traits/PageRendererTrait.php
- Classes/Traits/SourceSetViewHelperTrait.php
- Classes/Traits/TemplateVariableViewHelperTrait.php
- Classes/ViewHelpers/Condition/Form/HasValidatorViewHelper.php
- Classes/ViewHelpers/Condition/Form/IsRequiredViewHelper.php
- Classes/ViewHelpers/Condition/Iterator/ContainsViewHelper.php
- Classes/ViewHelpers/Content/Random/GetViewHelper.php
- Classes/ViewHelpers/Format/ReplaceViewHelper.php
- Classes/ViewHelpers/Iterator/ColumnViewHelper.php
- Classes/ViewHelpers/Iterator/PopViewHelper.php
- Classes/ViewHelpers/Iterator/PushViewHelper.php
- Classes/ViewHelpers/Iterator/RangeViewHelper.php
- Classes/ViewHelpers/Iterator/ReverseViewHelper.php
- Classes/ViewHelpers/Iterator/ShiftViewHelper.php
- Classes/ViewHelpers/Iterator/SliceViewHelper.php
- Classes/ViewHelpers/Iterator/UniqueViewHelper.php
- Classes/ViewHelpers/Iterator/ValuesViewHelper.php
- Classes/ViewHelpers/LViewHelper.php
- Classes/ViewHelpers/Media/ExistsViewHelper.php
- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Media/PictureViewHelper.php
- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
- Classes/ViewHelpers/Page/InfoViewHelper.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
- Classes/ViewHelpers/Uri/GravatarViewHelper.php
- Classes/ViewHelpers/Variable/ExtensionConfigurationViewHelper.php
> More Cleanups

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
Based on #1119 , so please merge the other one first.
> Fal misassignments

- Classes/Service/PageService.php
> [BUGFIX] Correct treatment of external urls

- Classes/Service/PageService.php
> [BUGFIX] Use correct scheme for external URLs

- .travis.yml
- composer.json
Ready for merging. Coverage drop reason is unknown but I suspect the coverage hasn't been reported correctly for a while.
> [TASK] Implement new fluidtypo3-development tools

- Classes/ViewHelpers/Format/HashViewHelper.php
- Tests/Unit/ViewHelpers/Format/HashViewHelperTest.php
> [FEATURE] Add `v:format.hash`

- Classes/ViewHelpers/Iterator/RandomViewHelper.php
Also converts the ViewHelper to static calling - does
not change any behavior.
> [BUGFIX] Fix v:iterator.random with empty input array

- Classes/ViewHelpers/Count/BytesViewHelper.php
- Classes/ViewHelpers/Count/LinesViewHelper.php
- Classes/ViewHelpers/Count/SubstringViewHelper.php
- Classes/ViewHelpers/Count/WordsViewHelper.php
- Tests/Unit/ViewHelpers/Count/BytesViewHelperTest.php
- Tests/Unit/ViewHelpers/Count/LinesViewHelperTest.php
- Tests/Unit/ViewHelpers/Count/SubstringViewHelperTest.php
- Tests/Unit/ViewHelpers/Count/WordsViewHelperTest.php
Counters for:
* Bytes
* Lines
* Substring occurrences
* Words
> [FEATURE] Add suite of counter ViewHelpers

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Render/AbstractRenderViewHelper.php
- Classes/ViewHelpers/Render/AsciiViewHelper.php
- Classes/ViewHelpers/Render/CacheViewHelper.php
- Classes/ViewHelpers/Render/InlineViewHelper.php
- Classes/ViewHelpers/Render/RecordViewHelper.php
- Classes/ViewHelpers/Render/RequestViewHelper.php
- Classes/ViewHelpers/Render/TemplateViewHelper.php
- Classes/ViewHelpers/Render/UncacheViewHelper.php
- Tests/Unit/ViewHelpers/Render/RecordViewHelperTest.php
Partially convert AbstractContentViewHelper to static.
> [TASK] Implement compile bridge in Render scope

- Classes/ViewHelpers/Render/RequestViewHelper.php
- Testing if argument is an array.
- fetching request from controllerContext, cause there is no getRequest at the renderingContentext
- typing error static::repsontype -> static::$responsType
> [BUGFIX] RenderRequest ViewHelper

- Classes/ViewHelpers/Page/AbsoluteUrlViewHelper.php
- Classes/ViewHelpers/Page/InfoViewHelper.php
- Classes/ViewHelpers/Page/LanguageViewHelper.php
- Classes/ViewHelpers/Page/RootlineViewHelper.php
- Classes/ViewHelpers/Page/StaticPrefixViewHelper.php
Takes the low hanging fruit first - remaining ViewHelpers
in this scope require a bit more attention.
> [TASK] Implement compile bridge in Page scope, partially

- Classes/ViewHelpers/Once/AbstractOnceViewHelper.php
- Classes/ViewHelpers/Once/CookieViewHelper.php
- Classes/ViewHelpers/Once/InstanceViewHelper.php
- Classes/ViewHelpers/Once/SessionViewHelper.php
- Tests/Unit/ViewHelpers/Once/CookieViewHelperTest.php
- Tests/Unit/ViewHelpers/Once/InstanceViewHelperTest.php
- Tests/Unit/ViewHelpers/Once/SessionViewHelperTest.php
> [TASK] Convert Once suite of ViewHelpers to static callable

- Classes/ViewHelpers/Variable/GetViewHelper.php
> [DOC] Fix incorrect argument name

- Classes/ViewHelpers/Condition/Page/HasSubpagesViewHelper.php
> [BUGFIX] Add fallback for deprecated argument

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
Fixes #1173 . Fixes #1103 .
getSlideRecords function was not called.
> Fixes page sliding in page.resources.fal ViewHelper

- Classes/ViewHelpers/Iterator/ChunkViewHelper.php
> [BUGFIX] Convert non-arrays in v:iterator.chunk

- .travis.yml
Nobody cares about HHVM anymore... is what I hear.
> [TASK] Drop CI test on HHVM

- Classes/Traits/SourceSetViewHelperTrait.php
- Classes/ViewHelpers/Media/AbstractMediaViewHelper.php
- Classes/ViewHelpers/Media/AudioViewHelper.php
- Classes/ViewHelpers/Media/ExtensionViewHelper.php
- Classes/ViewHelpers/Media/FilesViewHelper.php
- Classes/ViewHelpers/Media/ImageViewHelper.php
- Classes/ViewHelpers/Media/SizeViewHelper.php
- Classes/ViewHelpers/Media/VideoViewHelper.php
- Classes/ViewHelpers/Uri/ImageViewHelper.php
- Tests/Unit/ViewHelpers/Media/ExtensionViewHelperTest.php
- Tests/Unit/ViewHelpers/Media/FilesViewHelperTest.php
- Tests/Unit/ViewHelpers/Media/SizeViewHelperTest.php
- Tests/Unit/ViewHelpers/Uri/ImageViewHelperTest.php
Also touches one Uri scope ViewHelper which uses the Trait.
> [TASK] Implement compile bridge in Media scope and related Trait

- Classes/ViewHelpers/UnlessViewHelper.php
> [BUGFIX] Add argument `condition` to UnlessViewHelper

- Classes/ViewHelpers/Extension/Path/ResourcesViewHelper.php
- Tests/Unit/ViewHelpers/Extension/Path/ResourcesViewHelperTest.php
> [BUGFIX] Make path site relative as specified

- Classes/ViewHelpers/Render/InlineViewHelper.php
> [BUGFIX] Use namespaces from arguments and pass required rendering context

- Documentation/Changelog/3.1.0.md
According to CHANGELOG.md the release date is wrong.
> Fix release date

- CHANGELOG.md
> [TASK] Correct release date for 3.1.0

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
The $pageUid was used in the query, so the contentUids only worked with elements on the same page.
Changes:
If using contentUids the language and enableFields are included to the conditions.
Only if no contentUids are given, the colPos and the pid are included to the query.
solves #1218
> [BUGFIX] If using contentUids a page id is obsolet

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
Respect showAccessRestrictedPages when calculating subMenuItems
> Respect showAccessRestrictedPages when calculating subMenuItems

- Classes/ViewHelpers/Render/RequestViewHelper.php
#1228 Missings "arguments" in RequestViewHelper
> [BUGFIX] Missings "arguments" in RequestViewHelper

- Classes/ViewHelpers/Menu/ListViewHelper.php
> [BUGFIX] Skip empty page records in list menu

- Classes/ViewHelpers/ConstViewHelper.php
- Classes/ViewHelpers/LViewHelper.php
- Classes/ViewHelpers/OrViewHelper.php
This is the last PR for setting the escaping behavior.
> [BUGFIX] Set escaping behavior in Vhs ViewHelpers

- Classes/Traits/ArrayConsumingViewHelperTrait.php
> [BUGFIX] Make ArrayConsumingViewHelperTrait::mergeArraysStatic static

- Classes/ViewHelpers/LViewHelper.php
> [BUGFIX] Avoid overwriting variable

- Classes/ViewHelpers/Page/InfoViewHelper.php
- Tests/Unit/ViewHelpers/Page/InfoViewHelperTest.php
> [BUGFIX] Consider backend context

- Classes/ViewHelpers/Menu/BrowseViewHelper.php
> [BUGFIX] Early return on empty menu

- Classes/ViewHelpers/Iterator/SortViewHelper.php
Resolves: #1270 
Please review this. It works here, but I most probably did not test everything.
> [BUGFIX] Make iterator.sort work when cached

- Classes/ViewHelpers/Condition/Form/HasValidatorViewHelper.php
- Classes/ViewHelpers/Condition/Iterator/ContainsViewHelper.php
- Classes/ViewHelpers/Security/AbstractSecurityViewHelper.php
- Classes/ViewHelpers/UnlessViewHelper.php
Of derived AbstractConditionViewHelper
Closes: #1274
> [BUGFIX] Add missing parent calls

- composer.json
https://getcomposer.org/doc/06-config.md#preferred-install
> [BUGFIX] Move preferred-install to config

- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
> [BUGFIX] Remove double url encoding

- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
> [BUGFIX] Allow overriding default with empty value

- Classes/ViewHelpers/Render/UncacheViewHelper.php
> [BUGFIX] Retrieve UncacheTemplateView through ObjectManager

- Classes/ViewHelpers/Media/PictureViewHelper.php
- Classes/ViewHelpers/Media/SourceViewHelper.php
> [TASK] Accept filereference objects, add css class attribute

- Classes/ViewHelpers/Page/BreadCrumbViewHelper.php
> [BUGFIX] Take option includeSpacers into account

- Classes/ViewHelpers/Format/Json/EncodeViewHelper.php
> [BUGFIX] Make dateTimeToUnixtimeMiliseconds static

- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
> [TASK] Remove deprecated calls

- Classes/Service/AssetService.php
> [BUGFIX] Insert placeholder before tag's last occurence

- Classes/ViewHelpers/Media/VideoViewHelper.php
> [BUGFIX] Use argument value

- Classes/ViewHelpers/Random/StringViewHelper.php
> [BUGFIX] Typo in argument name

- Classes/Service/AssetService.php
Respect the config settings
- TYPO3_CONF_VARS / SYS / createGroup
- TYPO3_CONF_VARS / SYS / fileCreateMask
- TYPO3_CONF_VARS / SYS / folderCreateMask
> [BUGFIX] Respect access config in asset service

- Classes/ViewHelpers/Iterator/ImplodeViewHelper.php
> [TASK] Set correct expected argument type

- .gitignore
- .travis.yml
- composer.json
The PR tries to iteratively find a new way to build the project
> [BUGFIX] Fix the build

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
> [BUGFIX] Fix if condition to check if array is *not* empty

- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
> [BUGFIX] Add additional sanity checks for colPos and uid-lists

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
Crossing them fingers...
Fixes: #1379
> [BUGFIX] Filter empty array indexes

- Classes/ViewHelpers/Media/AbstractMediaViewHelper.php
- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
Addresses #1364. To be honest I don't remember why url encoding was used in the first place here so chances are this breaks something else. Testing and feedback is highly appreciated.
> [BUGFIX] Don't urlencode image urls

- Classes/ViewHelpers/Media/AbstractMediaViewHelper.php
- Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
> [BUGFIX] Reimplement url encoding

- Classes/View/UncacheTemplateView.php
- Tests/Unit/View/UncacheTemplateViewTest.php
#1225709595: The Fluid template files "" could not be loaded.
> [BUGFIX] no controller context v:render.uncache

- Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
> [BUGFIX] Properly use shortcut target uid

- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
Resolves  #1391
THX @RozbehSharahi works for me.
> [BUGFIX] Find available languages

- ext_localconf.php
> [BUGFIX] Add nav_hide to rootline

- Classes/ViewHelpers/Iterator/ExtractViewHelper.php
- Tests/Unit/ViewHelpers/Iterator/ExtractViewHelperTest.php
> Handle empty array in ExtractViewHelper

- Classes/Service/AssetService.php
- Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
- Classes/ViewHelpers/Media/PdfThumbnailViewHelper.php
Since TYPO3 8.0 publicly accessible files should be written to typo3temp/assets/.
[See TYPO3 Core Task #72580](https://forge.typo3.org/issues/72580)
> [TASK] Write publicly accessible files to typo3temp/assets/

- ext_emconf.php
> [TASK] Raise allowed PHP version

- Classes/ViewHelpers/Format/Placeholder/LipsumViewHelper.php
Removed an unreachable statement which got flagged by our CI pipeline
> [BUGFIX] Remove unreachable statement in LipsumViewHelper.php

- ext_localconf.php
> [BUGFIX] Fixes #1482

- Classes/ViewHelpers/Render/RequestViewHelper.php
See https://github.com/FluidTYPO3/vhs/pull/1427#issuecomment-404480933
> [BUGFIX] Correctly distinguish request and ViewHelper arguments

- ext_emconf.php
Officially declare support for TYPO3 v9.4
> [TASK] Update TYPO3 constraint in extension information

- Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php
- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
And remove unnecessary code from FalViewHelper
Should solve #1524
> [BUGFIX] Remove HiddenRestriction in Preview Mode

- Classes/Utility/CoreUtility.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
> [TASK] Country flags changed from SVG to PNG

- Classes/ViewHelpers/Format/TidyViewHelper.php
> Do not escape output for f:format.tidy

- Classes/ViewHelpers/Media/AudioViewHelper.php
> [BUGFIX] Use preload argument value for f:media.audio

- Classes/Service/PageService.php
also use RootlineUtility by default
> [BUGFIX] #1680 fixed rootline to filter correct by pageUid

- Classes/ViewHelpers/Page/Resources/FalViewHelper.php
Taken from https://github.com/FluidTYPO3/vhs/issues/1618#issuecomment-579699504
> Usage uid/parameter recommendations for v:page.resources.fal

- Classes/Service/AssetService.php
Bugfix for PHP8 while updating a content element
>  Update AssetService.php for PHP 8

- Classes/ViewHelpers/Media/ImageViewHelper.php
> [BUGFIX] always add alt attribute to media.image

- Classes/Traits/SlideViewHelperTrait.php
https://github.com/FluidTYPO3/vhs/issues/1878
> [BUGFIX] Fix FAL record slide limit calculation problem

- Classes/Utility/DoctrineQueryProxy.php
- Classes/ViewHelpers/Condition/Page/IsLanguageViewHelper.php
- Classes/ViewHelpers/Content/AbstractContentViewHelper.php
- Classes/ViewHelpers/Content/InfoViewHelper.php
- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
- Classes/ViewHelpers/Resource/AbstractResourceViewHelper.php
- Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php
- Classes/ViewHelpers/Resource/Record/FalViewHelper.php
- phpstan-baseline.neon
- phpstan.neon
> [BUGFIX] Relax return type for potential doctrine legacy version

- Classes/ViewHelpers/Condition/Context/IsProductionViewHelper.php
- Classes/ViewHelpers/Condition/Context/IsTestingViewHelper.php
- Classes/ViewHelpers/Condition/Form/HasValidatorViewHelper.php
- Classes/ViewHelpers/Condition/Iterator/ContainsViewHelper.php
- Classes/ViewHelpers/Condition/Page/HasSubpagesViewHelper.php
- Classes/ViewHelpers/Condition/Page/IsLanguageViewHelper.php
- Classes/ViewHelpers/Condition/String/ContainsViewHelper.php
- Classes/ViewHelpers/Condition/String/IsLowercaseViewHelper.php
- Classes/ViewHelpers/Condition/String/IsNumericViewHelper.php
- Classes/ViewHelpers/Condition/String/IsUppercaseViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsArrayViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsBooleanViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsDomainObjectViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsFloatViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsInstanceOfViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsIntegerViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsObjectViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsQueryResultViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsStringViewHelper.php
- Classes/ViewHelpers/Condition/Type/IsTraversableViewHelper.php
- Classes/ViewHelpers/Extension/LoadedViewHelper.php
- Classes/ViewHelpers/Media/ExistsViewHelper.php
- Classes/ViewHelpers/Once/AbstractOnceViewHelper.php
- Classes/ViewHelpers/Security/AbstractSecurityViewHelper.php
- Classes/ViewHelpers/Security/DenyViewHelper.php
- Classes/ViewHelpers/UnlessViewHelper.php
- Tests/Unit/ViewHelpers/Condition/Context/IsBackendViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsCliViewHelperTest.php
- Tests/Unit/ViewHelpers/Condition/Context/IsFrontendViewHelperTest.php
- Tests/Unit/ViewHelpers/Security/DenyViewHelperTest.php
Follows current practice in Fluid.
> [BUGFIX] Replace all evaluateCondition methods with verdict methods
